package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// OverrideEntry describes a service port override.
type OverrideEntry struct {
	ServiceName   string
	HostPort      int
	ContainerPort int
}

// GenerateOverride creates a temporary override file that remaps host ports.
// Returns the path to the created override file.
func GenerateOverride(entries []OverrideEntry) (string, error) {
	tmpDir, err := os.MkdirTemp("", "portless-docker-")
	if err != nil {
		return "", fmt.Errorf("failed to create temp directory: %w", err)
	}

	overridePath := filepath.Join(tmpDir, "override.yml")

	// Sort entries by service name for deterministic output.
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ServiceName < entries[j].ServiceName
	})

	content := "# Auto-generated by portless-docker. DO NOT EDIT.\nservices:\n"
	for _, e := range entries {
		content += fmt.Sprintf("  %s:\n    ports: !override\n      - \"%d:%d\"\n",
			e.ServiceName, e.HostPort, e.ContainerPort)
	}

	if err := os.WriteFile(overridePath, []byte(content), 0644); err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to write override file: %w", err)
	}

	return overridePath, nil
}

// RemoveOverride deletes the override file and its parent temp directory.
func RemoveOverride(overridePath string) error {
	if overridePath == "" {
		return nil
	}
	dir := filepath.Dir(overridePath)
	return os.RemoveAll(dir)
}
